In [1]:
import numpy as np


In [13]:
## Basic array creations
arr = np.array([1,2,3,4])
print(arr)

##list 
a = [1,2,3,4, "hello", 3.2]
a

## converting list to array
np.array(a)

## will convert everything into floats
a = [1,2,3,4,3.2]
np.array(a)

[1 2 3 4]


array([1. , 2. , 3. , 4. , 3.2])

In [ ]:
## creating 2 dimensional array
l = [[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

## Array Generation function 

In [17]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
##generating zer
arr = np.zeros((4,8))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [175]:
arr = np.linspace(1,6,5)
print(arr)

# [[ ]] -> vectors 
# [] -> matrix
# 0 to 1 is normatlization
# 3 to -3 is standardization

[1.   2.25 3.5  4.75 6.  ]


In [62]:
## Random generation fucntions
np.random.randn(10)


array([ 0.30960594,  0.47441388,  1.63016372, -1.70218249,  0.19097934,
       -1.41628807,  0.32920959,  0.019575  ,  0.49110378,  1.1791396 ])

In [33]:
np.random.randint(10,23,19)

array([13, 21, 12, 11, 13, 17, 12, 15, 16, 17, 14, 10, 13, 11, 21, 15, 13,
       10, 22], dtype=int32)

Array Attributes

Attributes are kind of var defined inside class
Methods are what functions are defined inside a class

In [34]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
arr.shape

(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int64')

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.min()
arr.max()
arr.sum()

np.int64(45)

In [44]:
arr.sum()

np.int64(45)

In [47]:
np.sum(arr, axis = 0)    
                        |
                        \/

SyntaxError: invalid syntax (3087967230.py, line 1)

In [46]:
np.sum(arr, axis = 1)  ->

array([ 6, 15, 24])

In [48]:
arr.mean()

np.float64(5.0)

In [50]:
arr.std()

np.float64(2.581988897471611)

In [51]:
arr.argmax() 
##will return index 

np.int64(8)

Resizing and Reshaping

In [59]:
arr = np.arange(1,31) 
arr
## will return index

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [61]:
import numpy as np

In [66]:
arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [67]:
arr[6]

np.int64(17)

In [70]:
arr[1:5]

array([12, 13, 14, 15])

In [71]:
arr[:5]

array([11, 12, 13, 14, 15])

In [72]:
arr[5:]

array([16, 17, 18, 19, 20])

In [73]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [74]:
arr[3::2]

array([14, 16, 18, 20])

NUMPY INDEXING AND SLICINF OF MATRIX

In [79]:
arr = np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [80]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [81]:
arr[0]

array([1, 2, 3, 4, 5])

In [98]:
arr[0,3]

np.int64(4)

In [110]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [111]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
## rows are from up to down  , columns are from left to right

In [114]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

In [116]:
arr[2:, 0:2]

array([[11, 12],
       [16, 17],
       [21, 22],
       [26, 27]])

BOOLEAN INDEXING 

In [117]:
bool_index = arr%2 == 0
print(bool_index)

[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


In [ ]:
arr = arr[bool_index]
print(arr)

In [ ]:
ARRAY OPERATIONS 


In [123]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)

[1 2 3 4 5]


In [124]:
a2

array([ 6,  7,  8,  9, 10])

In [125]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [126]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [127]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [128]:
a1 // a2

array([0, 0, 0, 0, 0])

In [129]:
a1 % a2

array([1, 2, 3, 4, 5])

Broad Casting (adding elements)

In [133]:
l = [10,20,30,40,50]
arr = np.array(l)
arr + 10

array([20, 30, 40, 50, 60])

Deep and shallow copy

In [139]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [146]:
slice = a[:5]
slice=slice * 10
print(slice)
print(a)
##changes will be made in the main list, in array it will create a copy and make changes there(shallow copy), (deep copy) will make changes in the main arr
##slice will create a new arr

[10 20 30 40 50]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [153]:
import numpy as np
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [154]:
A

array([[1, 2],
       [3, 4]])

In [155]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [156]:
A.T

array([[1, 3],
       [2, 4]])

In [157]:
B.T

array([[5, 7],
       [6, 8]])

ADVANCED ARRAY MANIPULATION

In [ ]:
##STACKING OF ARRAYS (only vectors can be used )

In [161]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [165]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Splitting Array 

In [168]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [171]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [172]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]