In [4]:
import numpy as np 

In [6]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
print(s)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [7]:
###adding total sum
s.sum()

np.int64(405)

In [18]:
##row sum
row = np.sum(s, axis = 1)
row == 45
for i in row:
    print(i)

45
45
45
45
45
45
45
45
45


In [16]:
## column axis
b = np.sum(s, axis = 0)
b == 45
for i in b:
    print(i)

45
45
45
45
45
45
45
45
45


In [19]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [20]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [21]:
s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [79]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [28]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [30]:
# get the shape of the data
data.shape

(5, 3)

In [38]:
# find the avg of the stud
np.mean(data[:,0])

np.float64(18.4)

In [41]:
#extract math marks 
data[:,1]

array([85, 92, 76, 65, 90])

In [42]:
#highest science marks
np.max(data[:,2])

np.int64(95)

In [44]:
#students who scored more then 90 in math
data[data[:,1]>90]

array([False, False,  True, False, False])

In [51]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [52]:
#adding plus 5
data[:,1] + 5


array([90, 97, 81, 70, 95])

In [57]:
#find how many are younger then 19
len(data[data[:,0] <= 19])

4

In [64]:
# calaulate the avg of all the marks
np.mean(data[:,1:3], axis = 0)

array([81.6, 83.2])

In [69]:
#get data of students who scored atlead 80 in 2 s
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [77]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])